language: php
dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

matrix:
  allow_failures:
    - php: 7.0
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - if [[ $TRAVIS_PHP_VERSION == '5.3' ]]; then composer require container-interop/container-interop:1.2 filp/whoops rdlowrey/auryn twig/twig http-interop/http-middleware:^0.4.1 --dev; fi
  - if [[ $TRAVIS_PHP_VERSION != '5.3' ]]; then composer require container-interop/container-interop:1.2 filp/whoops league/container nikic/fast-route phroute/phroute rdlowrey/auryn twig/twig zendframework/zend-diactoros zendframework/zend-stratigility http-interop/http-middleware:^0.4.1 --dev; fi

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
