language: php
dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - composer require container-interop/container-interop filp/whoops rdlowrey/auryn twig/twig http-interop/http-middleware:~0.4.1
  - if [[ $TRAVIS_PHP_VERSION != '5.3' ]]; then composer require league/container:~2.4 nikic/fast-route phroute/phroute zendframework/zend-diactoros zendframework/zend-stratigility --dev; fi
  - if [[ $TRAVIS_PHP_VERSION == '7.1' ]]; then composer require zendframework/zend-stratigility:~2.0 && composer update --dev; fi
  - if [[ $TRAVIS_PHP_VERSION == '7.2' ]]; then composer require zendframework/zend-stratigility:~2.0 && composer update --dev; fi
  - if [[ $TRAVIS_PHP_VERSION == 'hhvm' ]]; then composer require zendframework/zend-stratigility:~2.0 && composer update --dev; fi

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi