language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - composer require container-interop/container-interop filp/whoops rdlowrey/auryn twig/twig http-interop/http-middleware
  - if [[ $TRAVIS_PHP_VERSION != '5.3' ]]; then composer require league/container:~2.4 nikic/fast-route phroute/phroute zendframework/zend-diactoros zendframework/zend-stratigility --dev; fi
  - if [[ $TRAVIS_PHP_VERSION == '7.1' ]]; then composer require zendframework/zend-stratigility:~2.0 && composer update --dev; fi
  - if [[ $TRAVIS_PHP_VERSION == '7.2' ]]; then composer require zendframework/zend-stratigility:~2.0 && composer update --dev; fi
  - if [[ $TRAVIS_PHP_VERSION == 'hhvm' ]]; then composer require zendframework/zend-stratigility:~2.0 && composer update --dev; fi

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi