on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '5.3', '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3' ]
    name: Run Unit Test on PHP ${{ matrix.php-versions }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Check the PHP version
      run: php -v

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install third-party packages for PHP 5.3
      if: ${{ matrix.php-versions == '5.3' }}
      run: composer require http-interop/http-middleware:^0.4.1 twig/twig --dev

    - name: Install third-party packages not for PHP 5.3
      if: ${{ matrix.php-versions != '5.3' }}
      run: composer require filp/whoops league/container nikic/fast-route phroute/phroute rdlowrey/auryn twig/twig zendframework/zend-diactoros http-interop/http-middleware:^0.4.1 --dev

    - name: Install third-party packages for PHP 5.4
      if: ${{ matrix.php-versions == '5.4' }}
      run: composer require zendframework/zend-stratigility --dev

    - name: Install third-party packages for PHP 5.5
      if: ${{ matrix.php-versions == '5.5' }}
      run: composer require zendframework/zend-stratigility --dev

    - name: Install third-party packages for PHP 7.1
      if: ${{ matrix.php-versions == '7.1' }}
      run: composer require zendframework/zend-stratigility --dev

    - name: Install third-party packages for PHP 7.2
      if: ${{ matrix.php-versions == '7.2' }}
      run: composer require zendframework/zend-stratigility --dev

    - name: Install third-party packages for PHP 7.3
      if: ${{ matrix.php-versions == '7.3' }}
      run: composer require zendframework/zend-stratigility --dev

    - name: Install third-party packages for PHP 7.4
      if: ${{ matrix.php-versions == '7.4' }}
      run: composer require zendframework/zend-stratigility --dev

    - name: Run test suite
      run: vendor/bin/phpunit --coverage-clover=coverage.clover

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4-beta
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}