on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
    name: Run Unit Test on PHP ${{ matrix.php-versions }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        fetch-depth: 10

    - name: Check the PHP version
      run: php -v

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install Composer packages not for PHP 5.3
      if: ${{ matrix.php-versions != '5.3' }}
      run: composer require nikic/fast-route phroute/phroute twig/twig zendframework/zend-diactoros http-interop/http-middleware:^0.4.1 league/container:~2.4 --dev

    - name: Install Composer packages for PHP 7.1
      if: ${{ matrix.php-versions == '7.1' }}
      run: composer require zendframework/zend-stratigility:~2.0 --dev

    - name: Install Composer packages for PHP 7.2
      if: ${{ matrix.php-versions == '7.2' }}
      run: composer require zendframework/zend-stratigility:~2.0 --dev

    - name: Install Composer packages for PHP 7.3
      if: ${{ matrix.php-versions == '7.3' }}
      run: composer require zendframework/zend-stratigility:~2.0 --dev

    - name: Install Composer packages for PHP 7.4
      if: ${{ matrix.php-versions == '7.4' }}
      run: composer require zendframework/zend-stratigility:~2.0 --dev

    - name: Run test suite
      run: vendor/bin/phpunit --coverage-clover coverage.xml .

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4-beta
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    # - name: Run test suite
    #   run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

    # - name: Send results to Scrutinizer CI
    #   run: vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover