on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
    name: Run Unit Test on PHP ${{ matrix.php-versions }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Check the PHP version
      run: php -v

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install third-party Composer packages
      run: composer require league/container:~2.4 nikic/fast-route:~2.1 phroute/phroute zendframework/zend-diactoros zendframework/zend-stratigility http-interop/http-middleware

    # - name: Install Composer packages for PHP 7.1
    #   if: ${{ steps.setup-php.outputs.php-version == '7.1' }}
    #   run: composer require zendframework/zend-stratigility:~2.0

    # - name: Install Composer packages for PHP 7.2
    #   if: ${{ steps.setup-php.outputs.php-version == '7.2' }}
    #   run: composer require zendframework/zend-stratigility:~2.0

    # - name: Install Composer packages for PHP 7.3
    #   if: ${{ steps.setup-php.outputs.php-version == '7.3' }}
    #   run: composer require zendframework/zend-stratigility:~2.0

    # - name: Install Composer packages for PHP 7.4
    #   if: ${{ steps.setup-php.outputs.php-version == '7.4' }}
    #   run: composer require zendframework/zend-stratigility:~2.0

    - name: Run test suite
      run: vendor/bin/phpunit